on:
    push:
        branches:
          - main

jobs:
    compress:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          - name: Setup Node
            uses: actions/setup-node@v3
            with:
                node-version: '20'
            
          - name: Install JSON minification tool
            run: npm install -g json-minify
            
          - name: Find and minify JSON files
            run: |
                find . -name "*.json" -exec sh -c 'cat {} | json-minify > {}.tmp && mv {}.tmp {}' \;

          - name: Archive Files
            run: zip -r softer-wool.mcpack texts textures manifest.json pack_icon.png

          - uses: actions/upload-artifact@v4
            with:
                name: softer-wool
                path: ./softer-wool.mcpack
